# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Alumni SMUNIC 2003
tagline:          'SMUNIC 2003'
description:      'Website alumnus SMUNIC angkatan tahun 2003.'
url:              https://smunic2003.github.io/web/
baseurl:          '/web/'

author:
  name:           'Oki Dwi Yulianto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
