# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Alumni SMUNIC 2003
tagline:          'Masalalu bukanlah kenangan tetapi guru terbaik'
description:      'Website alumnus SMUNIC angkatan tahun 2003.'
url:              http://smunicduaributi.ga
baseurl:          '/web/'

author:
  name:           'Oki Dwi Yulianto'
  url:            https://twitter.com/okidwiyulianto

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/smunic2003/web.git
