# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Alumnus SMUNIC 2003
tagline:             '"Masa lalu bukanlah kenangan, tetapi guru terbaik"'
description:         'Website alumnus SMA Negeri 1 Cilacap angkatan 2003'
url:                 http://lanyon.getpoole.com
baseurl:             '/web'
paginate:            5

# About/contact
author:
  name:              Oki Dwi Yulianto
  url:               https://twitter.com/okidwiyulianto
  email:             sman1clp2013@gmail.com

# Custom vars
version:             1.0.0
